a=int(input("Enter number"))
b=int(input("Enter number"))
c=int(input("Enter number"))
d=int(input("Enter number"))
e=int(input("Enter number"))
sum1=a+b+c+d+e
avg=sum1/5
print("Sum is =",sum1)
print("Avg is =",avg)
